name: Build & Push fr-api with Kaniko

on:
  push:
    branches: [ main ]
    paths:
      - 'mlops/APIs/fr-api/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: fr-api-runners
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Push with Kaniko
        uses: docker://gcr.io/kaniko-project/executor:v1.23.0-debug
        with:
          entrypoint: /kaniko/executor
          args: |
            --context ./mlops/APIs/fr-api
            --dockerfile ./mlops/APIs/fr-api/Dockerfile
            --destination harbor.nimar.gov.pk/mlops/fr-client:latest
            --destination harbor.nimar.gov.pk/mlops/fr-client:${{ github.sha }}
            --cache=true
            --cache-repo=harbor.nimar.gov.pk/mlops/fr-client-cache
            --insecure-registry harbor.nimar.gov.pk
            --push-retry=3
            --verbosity=info

# name: Build & Push fr-api with Kaniko

# on:
#   push:
#     branches: [ main ]
#     paths:
#       - 'mlops/APIs/fr-api/**'
#   workflow_dispatch:

# jobs:
#   build-and-push:
#     runs-on: fr-api-runners

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Build and Push with Kaniko
#         uses: docker://gcr.io/kaniko-project/executor:v1.23.0-debug
#         with:
#           entrypoint: /kaniko/executor
#           args: |
#             --context ./mlops/APIs/fr-api
#             --dockerfile ./mlops/APIs/fr-api/Dockerfile
#             --destination harbor.nimar.gov.pk/mlops/fr-client:latest
#             --destination harbor.nimar.gov.pk/mlops/fr-client:${{ github.sha }}
#             --cache=true
#             --cache-repo=harbor.nimar.gov.pk/mlops/fr-client-cache
#             --insecure-registry harbor.nimar.gov.pk
#             --push-retry=3
#             --force   # optional
