name: Build & Push fr-api to DockerHub

on:
  push:
    branches: [main]
    paths:
      - 'mlops/APIs/fr-api/**'
  pull_request:
    branches: [main]
    paths:
      - 'mlops/APIs/fr-api/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ./mlops/APIs/fr-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: haiderali11/fr-client:latest
          cache-from: type=registry,ref=haiderali11/fr-client:latest
          cache-to: type=inline
